import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" type="image/ico" href="/assets/Tortuga_durisima_logo.ico" />
      <meta name="descripcion" content="Desripción de la página "/>
      <title>Miquel Gómez Corral</title>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
